# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_hcd" "ehci_pci" "ahci" "usb_storage" ];
  boot.initrd.luks.devices = [
    { name = "ROOT"; device = "/dev/sda3"; preLVM = true; }
  ];
  boot.kernelModules = [ "kvm-intel" "tp_smapi" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.tp_smapi ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ed76c120-ddab-4a40-8f43-f2c9ad08aa45";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/81090fea-0337-4632-8ac4-d991f61a6751";
      fsType = "ext2";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/9ea10f92-1bba-4a9a-8cb9-befcffe6e2cb"; }
    ];

  nix.maxJobs = 4;
}
